# Generated by Django 4.0.5 on 2022-07-07 14:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0003_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='ques',
            name='likes',
            field=models.ManyToManyField(related_name='Ques_post', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
