# Generated by Django 4.0.5 on 2022-07-09 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ques',
            name='likes',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
