# Generated by Django 4.0.5 on 2022-08-10 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_challenge_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='sno',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
